# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'CIC Judging' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CIC Judging
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'FontAwesome.swift'

end
