# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CIC Judging' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :ios

  # Pods for CIC Judging
  pod 'Firebase/Auth'

end
